# Generated by Django 2.2.10 on 2020-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_details', models.TextField()),
                ('thumnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
